#!/bin/sh
# test program to simulate https://github.com/plandes/synconf

USAGE="usage: $0 -a listmnemonics"

if [ $# -ne 2 ] ; then
    echo $USAGE
    exit 1
fi

if [ "$1" != "-a" ] || [ "$2" != "listmnemonics" ] ; then
    echo $USAGE
    exit 1
fi

echo "laptop"
echo "usb"
